function [vAdmm, info] = optimize_ris_admm(Hsr, Hrd, params, options)
%OPTIMIZE_RIS_ADMM RIS phase optimization with closed-form ADMM updates.
%
%   Inputs:
%       Hsr     - Source/Radar-to-RIS channel, size Nr x Nt.
%       Hrd     - Stage-2 RIS-domain target/return effective channel, size
%                 Nr x Nr. The project convention is fixed as:
%                 Heff = Hsr' * diag(v) * Hrd * diag(v)' * Hsr.
%       params  - Struct from config/paper_params.m.
%       options - Optional struct:
%                 initialV  : Nr x 1 unit-modulus initial RIS phase.
%                 maxIter   : maximum ADMM iterations.
%                 tolerance : convergence tolerance.
%                 rho       : ADMM penalty. It is increased if needed so
%                             rho*I + T is numerically positive definite.
%
%   Outputs:
%       vAdmm - RIS phase vector, size Nr x 1, with |v_i| = 1.
%       info  - Struct containing objectiveHistory, quadraticObjectiveHistory,
%               primalResidualHistory, dualResidualHistory, numIter,
%               converged, rho, method, T, and model notes.
%
%   ADMM form:
%       The paper uses an extended vector x in C^(Nr+1), unit-modulus u,
%       and multiplier mu:
%
%           u = exp(1j * angle(x - mu/rho))
%           x = (rho*I + T)^(-1) * (rho*u + mu)
%           mu = mu + rho*(u - x)
%
%       Under the current Hrd: Nr x Nr project convention, the executable
%       path gain ||Heff||_F^2 is quartic in v and cannot be represented by
%       the paper's quadratic T matrix without changing the model. This
%       function therefore constructs a dimension-consistent quadratic ADMM
%       approximation from the Hermitian part of trace(Heff):
%
%           trace(Heff) = v' * Q * v, Q = (Hsr*Hsr') .* transpose(Hrd)
%
%       The ADMM minimizes 0.5*x'*T*x with:
%
%           T(1:Nr,1:Nr) = -0.5*(Q + Q')
%           T(Nr+1,Nr+1) = 0
%
%       The final RIS phase is recovered as v = exp(1j*angle(x(1:Nr)/x(end))).
%       This is explicitly a quadratic ADMM approximation, not an exact
%       reproduction of the paper's T matrix.

arguments
    Hsr {mustBeNumeric}
    Hrd {mustBeNumeric}
    params struct
    options struct = struct()
end

Nr = size(Hsr, 1);
if size(Hrd, 1) ~= Nr || size(Hrd, 2) ~= Nr
    error("RIS_MIMO_FMCW:DimensionMismatch", ...
        "Hrd must be Nr x Nr. Got Hrd %s and Nr=%d.", mat2str(size(Hrd)), Nr);
end

maxIter = get_option(options, "maxIter", params.optim.maxIter);
tolerance = get_option(options, "tolerance", min(params.optim.tolerances));
rhoRequested = get_option(options, "rho", 1);

if isfield(options, "initialV")
    v0 = project_unit_modulus(options.initialV(:));
else
    v0 = exp(1j .* 2 .* pi .* rand(Nr, 1));
end

[T, qMatrix, tMeta] = build_quadratic_t_matrix(Hsr, Hrd);
minEigT = min(real(eig(T)));
rhoMinimum = max(0, -minEigT) + 1e-9;
rho = max(rhoRequested, 1.05 * rhoMinimum);

x = [v0; 1];
mu = zeros(Nr + 1, 1);
systemMatrix = rho .* eye(Nr + 1) + T;

objectiveHistory = zeros(maxIter + 1, 1);
quadraticObjectiveHistory = zeros(maxIter + 1, 1);
primalResidualHistory = zeros(maxIter, 1);
dualResidualHistory = zeros(maxIter, 1);

vCurrent = recover_phase_from_extended_x(x, Nr);
objectiveHistory(1) = compute_path_gain(Hsr, Hrd, vCurrent);
quadraticObjectiveHistory(1) = real(0.5 .* (x' * T * x));

bestV = vCurrent;
bestObjective = objectiveHistory(1);
converged = false;

for iter = 1:maxIter
    xPrevious = x;

    u = project_unit_modulus(x - (mu ./ rho));
    x = systemMatrix \ (rho .* u + mu);
    mu = mu + rho .* (u - x);

    vCurrent = recover_phase_from_extended_x(x, Nr);
    trueObjective = compute_path_gain(Hsr, Hrd, vCurrent);
    quadraticObjective = real(0.5 .* (x' * T * x));

    objectiveHistory(iter + 1) = trueObjective;
    quadraticObjectiveHistory(iter + 1) = quadraticObjective;
    primalResidualHistory(iter) = norm(u - x);
    dualResidualHistory(iter) = rho .* norm(x - xPrevious);

    if trueObjective >= bestObjective
        bestObjective = trueObjective;
        bestV = vCurrent;
    end

    primalOk = primalResidualHistory(iter) < sqrt(Nr + 1) .* tolerance;
    dualOk = dualResidualHistory(iter) < sqrt(Nr + 1) .* tolerance;
    if iter > 1 && primalOk && dualOk
        converged = true;
        break;
    end
end

numIter = iter;
vFinal = recover_phase_from_extended_x(x, Nr);

% Return the best true path-gain iterate generated by the closed-form ADMM.
% This safeguard uses only ADMM iterates; it does not use gradient search.
if bestObjective >= compute_path_gain(Hsr, Hrd, v0)
    vAdmm = bestV;
else
    vAdmm = vFinal;
end
vAdmm = project_unit_modulus(vAdmm);

info = struct();
info.method = "quadratic_admm_approximation";
info.paperLikeUpdates = true;
info.usesFiniteDifferenceGradient = false;
info.objective = "true objective logged as ||Heff||_F^2; ADMM optimizes quadratic trace(Heff) proxy";
info.objectiveHistory = objectiveHistory(1:numIter + 1);
info.quadraticObjectiveHistory = quadraticObjectiveHistory(1:numIter + 1);
info.primalResidualHistory = primalResidualHistory(1:numIter);
info.dualResidualHistory = dualResidualHistory(1:numIter);
info.numIter = numIter;
info.converged = converged;
info.rho = rho;
info.rhoRequested = rhoRequested;
info.rhoMinimum = rhoMinimum;
info.tolerance = tolerance;
info.initialObjective = objectiveHistory(1);
info.finalObjective = compute_path_gain(Hsr, Hrd, vAdmm);
info.bestObjective = bestObjective;
info.unitModulusMaxError = max(abs(abs(vAdmm) - 1));
info.T = T;
info.Q = qMatrix;
info.TMeta = tMeta;
info.dimension.x = [Nr + 1, 1];
info.dimension.u = [Nr + 1, 1];
info.dimension.mu = [Nr + 1, 1];
info.dimension.T = size(T);
end

function [T, Qh, meta] = build_quadratic_t_matrix(Hsr, Hrd)
Nr = size(Hsr, 1);
Rsr = Hsr * Hsr';
Q = Rsr .* transpose(Hrd);
Qh = 0.5 .* (Q + Q');

T = zeros(Nr + 1, Nr + 1);
T(1:Nr, 1:Nr) = -Qh;
T = 0.5 .* (T + T');

meta = struct();
meta.proxy = "real(trace(Heff)) = real(v^H * Qh * v)";
meta.QSize = size(Qh);
meta.TSize = size(T);
meta.note = "Quadratic proxy is dimension-consistent but not equal to ||Heff||_F^2.";
end

function value = get_option(options, fieldName, defaultValue)
if isfield(options, fieldName)
    value = options.(fieldName);
else
    value = defaultValue;
end
end

function v = recover_phase_from_extended_x(x, Nr)
denominator = x(Nr + 1);
if abs(denominator) < eps
    denominator = 1;
end
v = project_unit_modulus(x(1:Nr) ./ denominator);
end

function v = project_unit_modulus(z)
v = exp(1j .* angle(z));
zeroMask = abs(z) < eps;
v(zeroMask) = 1;
end
